version: '3'

volumes:
  node_modules:
  assets:

services:
  web:
    build: ./web
    command: flask run --host=0.0.0.0
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: 1
      OAUTHLIB_INSECURE_TRANSPORT: 1
    env_file:
      - ./web/web.env
    volumes:
      - ./web:/app
      - assets:/app/assets
    ports:
      - "5001:5000"
    depends_on:
      - assets

  assets:
    build:
      context: ./assets
    volumes:
      - assets:/dist
      - ./assets:/app
      - node_modules:/app/node_modules
      - ./node_modules:/pacakage/node_modules
    command: ./entrypoint.sh
