version: '3'

volumes:
  node_modules:
  assets:

services:
  nginx:
    build: ./nginx
    ports:
      - "8001:8001"
    volumes:
      - assets:/static
    depends_on:
      - web
    environment:
      WEB_PORT: 5000
    command: ./run.sh

  web:
    build: ./web
    command: flask run --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      OAUTHLIB_INSECURE_TRANSPORT: 1
    env_file:
      - ./web/web.env
    volumes:
      - ./web:/app
      - assets:/app/assets
    depends_on:
      - assets

  assets:
    build:
      context: ./assets
    volumes:
      - assets:/app/dist
      - ./assets:/app
      - node_modules:/app/node_modules
      - ./node_modules:/package/node_modules
    command: ./entrypoint.sh
